name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build setuptools-scm

      - name: Build package
        run: |
          python -m build -n --sdist --wheel

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: |
            ./dist/*.whl
            ./dist/*.tar.gz
          generate_release_notes: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
