name: Release and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release_and_publish:
    name: Release and Publish
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build the package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel

      - name: Get the package version
        run: |
          echo VERSION="$(python -c 'from configwebui import __version__; print(__version__)')" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: Release ${{ github.ref_name }}
          # body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload distribution files to GitHub Release (whl)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/configwebui_lucien-${{ env.VERSION }}-py3-none-any.whl
          asset_name: configwebui_lucien-${{ env.VERSION }}-py3-none-any.whl
          asset_content_type: application/octet-stream

      - name: Upload source tarball to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/configwebui_lucien-${{ env.VERSION }}.tar.gz
          asset_name: configwebui_lucien-${{ env.VERSION }}.tar.gz
          asset_content_type: application/octet-stream

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
