name: Build and publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    name: Build and publish release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools setuptools-scm wheel build

      - name: Build package
        run: |
          python -m build -n --sdist --wheel

      - name: Determine if this is a beta release
        id: check_beta_release
        env:
          CHECKER_CMD: "python utils/check_tag.py"
        run: |
          if [[ "${{ github.ref_name }}" == *-beta* ]]; then
            IS_BETA=1
          else
            IS_BETA=0
          fi
          echo "IS_BETA=$IS_BETA" >> $GITHUB_OUTPUT
      
      - name: Prepare release notes
        run: |
          if [ ! -f UPDATE.md ]; then
            echo "" > UPDATE.md
          fi
          if [ "${{ steps.check_beta_release.outputs.IS_BETA }}" == "1" ]; then
            echo "Notice: This is a pre-release, files will not be uploaded to [PyPI](https://pypi.org/project/configwebui-lucien/)." >> release_notes.md
          fi
          cat UPDATE.md >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release_notes.md
          prerelease: ${{ steps.check_beta_release.outputs.IS_BETA == '1' }}
          name: Release ${{ github.ref_name }}
          make_latest: ${{ steps.check_beta_release.outputs.IS_BETA == '0' }}
          files: |
            ./dist/*.whl
            ./dist/*.tar.gz
          generate_release_notes: true

      - name: Publish to PyPI
        if: steps.check_beta_release.outputs.IS_BETA == '0'
        uses: pypa/gh-action-pypi-publish@release/v1
