name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build setuptools-scm

      - name: Build package
        run: |
          python -m build -n --sdist --wheel

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: |
            ./dist/*.whl
            ./dist/*.tar.gz
          generate_release_notes: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  merge_dev_to_master:
    name: Merge dev -> master
    runs-on: ubuntu-latest
    needs: build_and_publish
    permissions:
      contents: write
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge dev into master
        run: |
          git fetch origin master
          git checkout master
          git merge --ff-only origin/dev
          git push origin master
